@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}


# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/?limit=5&offset=10
### Lista apenas 1 recado
GET {{baseUrl}}/recados/1
### Cria 1 recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Novo recado",
  "de": "Pedro",
  "para": "Camila",
  "lido": false,
  "data": "2025-09-10T17:39:45.556Z"
}
### Atualiza 1 recado
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
  "texto": "Novo recado dia 11",
  "de": "Camila",
  "para": "Joana",
  "lido": false,
  "data": "2025-09-11T17:39:45.556Z"
}
### Deleta 1 recado
DELETE {{baseUrl}}/recados/2
